import "dotenv/config";
import { db } from "@/db";
import { laptops } from "@/db/schema";

const laptopSeedData: (typeof laptops.$inferInsert)[] = [
  {
    sku: "APL-MBP14-M3P-18-512",
    slug: "macbook-pro-14-m3-pro-18gb-512gb",
    brand: "apple",
    model: "MacBook Pro 14",
    title: 'MacBook Pro 14" M3 Pro 18GB/512GB Space Black',
    description:
      "Laptop dla profesjonalistów z chipem M3 Pro, ekranem Liquid Retina XDR i do 18h pracy na baterii.",
    priceCents: 1099900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 12,
    ramGb: 18,
    storageGb: 512,
    screenInches: "14.2",
    weightGrams: 1600,
    batteryWh: 70,
    refreshRateHz: 120,
    cpuBrand: "apple",
    cpuModel: "Apple M3 Pro",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "macos",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "APL-MBA13-M3-8-256",
    slug: "macbook-air-13-m3-8gb-256gb",
    brand: "apple",
    model: "MacBook Air 13",
    title: 'MacBook Air 13" M3 8GB/256GB Midnight',
    description:
      "Ultralekki laptop bez wentylatora, idealny do pracy biurowej i nauki.",
    priceCents: 599900,
    compareAtPriceCents: 649900,
    currency: "PLN",
    quantity: 20,
    ramGb: 8,
    storageGb: 256,
    screenInches: "13.6",
    weightGrams: 1240,
    batteryWh: 52,
    refreshRateHz: 60,
    cpuBrand: "apple",
    cpuModel: "Apple M3",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "macos",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "DEL-XPS15-I7-16-1TB",
    slug: "dell-xps-15-i7-16gb-1tb",
    brand: "dell",
    model: "XPS 15",
    title: 'Dell XPS 15" Core i7-13700H 16GB/1TB RTX 4050',
    description:
      "Premium laptop dla twórców z ekranem OLED i dedykowaną kartą graficzną.",
    priceCents: 899900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 8,
    ramGb: 16,
    storageGb: 1024,
    screenInches: "15.6",
    weightGrams: 1860,
    batteryWh: 86,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Core i7-13700H",
    gpuType: "dedicated",
    gpuModel: "RTX 4050",
    storageType: "ssd",
    os: "windows",
    touchscreen: true,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "DEL-INS15-I5-8-512",
    slug: "dell-inspiron-15-i5-8gb-512gb",
    brand: "dell",
    model: "Inspiron 15",
    title: 'Dell Inspiron 15" Core i5-1235U 8GB/512GB',
    description: "Solidny laptop do domu i biura w rozsądnej cenie.",
    priceCents: 289900,
    compareAtPriceCents: 329900,
    currency: "PLN",
    quantity: 25,
    ramGb: 8,
    storageGb: 512,
    screenInches: "15.6",
    weightGrams: 1650,
    batteryWh: 54,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Core i5-1235U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: false,
    isActive: true,
  },
  {
    sku: "LEN-X1C-I7-16-512",
    slug: "lenovo-thinkpad-x1-carbon-i7-16gb-512gb",
    brand: "lenovo",
    model: "ThinkPad X1 Carbon Gen 12",
    title: "Lenovo ThinkPad X1 Carbon Gen 12 Core i7 16GB/512GB",
    description:
      "Biznesowy laptop premium, bardzo lekki, z certyfikatem MIL-STD.",
    priceCents: 799900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 10,
    ramGb: 16,
    storageGb: 512,
    screenInches: "14.0",
    weightGrams: 1120,
    batteryWh: 57,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Core i7-1355U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "LEN-LOQ15-R7-16-512",
    slug: "lenovo-loq-15-ryzen7-16gb-512gb",
    brand: "lenovo",
    model: "LOQ 15",
    title: 'Lenovo LOQ 15" Ryzen 7 7840HS 16GB/512GB RTX 4060',
    description: "Laptop gamingowy w przystępnej cenie z ekranem 144Hz.",
    priceCents: 549900,
    compareAtPriceCents: 599900,
    currency: "PLN",
    quantity: 15,
    ramGb: 16,
    storageGb: 512,
    screenInches: "15.6",
    weightGrams: 2300,
    batteryWh: 60,
    refreshRateHz: 144,
    cpuBrand: "amd",
    cpuModel: "Ryzen 7 7840HS",
    gpuType: "dedicated",
    gpuModel: "RTX 4060",
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "ASU-ROG13-I9-32-1TB",
    slug: "asus-rog-strix-i9-32gb-1tb",
    brand: "asus",
    model: "ROG Strix G16",
    title: 'ASUS ROG Strix G16" Core i9-13980HX 32GB/1TB RTX 4070',
    description:
      "Wydajny laptop gamingowy z ekranem 165Hz i topową kartą graficzną.",
    priceCents: 1199900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 6,
    ramGb: 32,
    storageGb: 1024,
    screenInches: "16.0",
    weightGrams: 2500,
    batteryWh: 90,
    refreshRateHz: 165,
    cpuBrand: "intel",
    cpuModel: "Core i9-13980HX",
    gpuType: "dedicated",
    gpuModel: "RTX 4070",
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "ASU-VIVO15-R5-8-512",
    slug: "asus-vivobook-15-ryzen5-8gb-512gb",
    brand: "asus",
    model: "VivoBook 15",
    title: 'ASUS VivoBook 15" Ryzen 5 7530U 8GB/512GB',
    description: "Uniwersalny laptop do codziennych zadań i nauki.",
    priceCents: 249900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 30,
    ramGb: 8,
    storageGb: 512,
    screenInches: "15.6",
    weightGrams: 1700,
    batteryWh: 42,
    refreshRateHz: 60,
    cpuBrand: "amd",
    cpuModel: "Ryzen 5 7530U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: false,
    isActive: true,
  },
  {
    sku: "HP-SPX14-I7-16-1TB",
    slug: "hp-spectre-x360-14-i7-16gb-1tb",
    brand: "hp",
    model: "Spectre x360 14",
    title: 'HP Spectre x360 14" Core i7-1355U 16GB/1TB',
    description: "Laptop 2w1 z ekranem dotykowym OLED, obraca się o 360°.",
    priceCents: 749900,
    compareAtPriceCents: 799900,
    currency: "PLN",
    quantity: 9,
    ramGb: 16,
    storageGb: 1024,
    screenInches: "13.5",
    weightGrams: 1360,
    batteryWh: 68,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Core i7-1355U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: true,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "HP-PAV15-I5-8-256",
    slug: "hp-pavilion-15-i5-8gb-256gb",
    brand: "hp",
    model: "Pavilion 15",
    title: 'HP Pavilion 15" Core i5-1334U 8GB/256GB',
    description: "Lekki laptop na start dla studentów i pracy biurowej.",
    priceCents: 219900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 18,
    ramGb: 8,
    storageGb: 256,
    screenInches: "15.6",
    weightGrams: 1750,
    batteryWh: 41,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Core i5-1334U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: false,
    isActive: true,
  },
  {
    sku: "MSI-KTG16-I9-32-2TB",
    slug: "msi-katana-16-i9-32gb-2tb",
    brand: "msi",
    model: "Katana 16",
    title: 'MSI Katana 16" Core i9-13900H 32GB/2TB RTX 4070',
    description: "Mocny laptop gamingowy z dużą przestrzenią dyskową.",
    priceCents: 949900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 7,
    ramGb: 32,
    storageGb: 2048,
    screenInches: "16.0",
    weightGrams: 2600,
    batteryWh: 90,
    refreshRateHz: 144,
    cpuBrand: "intel",
    cpuModel: "Core i9-13900H",
    gpuType: "dedicated",
    gpuModel: "RTX 4070",
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "MSI-MOD14-R5-16-512",
    slug: "msi-modern-14-ryzen5-16gb-512gb",
    brand: "msi",
    model: "Modern 14",
    title: 'MSI Modern 14" Ryzen 5 7530U 16GB/512GB',
    description: "Kompaktowy laptop biznesowy w dobrej cenie.",
    priceCents: 279900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 14,
    ramGb: 16,
    storageGb: 512,
    screenInches: "14.0",
    weightGrams: 1400,
    batteryWh: 39,
    refreshRateHz: 60,
    cpuBrand: "amd",
    cpuModel: "Ryzen 5 7530U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: false,
    isActive: true,
  },
  {
    sku: "ACR-SWIFT3-R7-16-512",
    slug: "acer-swift-3-ryzen7-16gb-512gb",
    brand: "acer",
    model: "Swift 3",
    title: 'Acer Swift 3" Ryzen 7 7735U 16GB/512GB',
    description: "Lekki ultrabook z dobrym stosunkiem ceny do wydajności.",
    priceCents: 329900,
    compareAtPriceCents: 359900,
    currency: "PLN",
    quantity: 16,
    ramGb: 16,
    storageGb: 512,
    screenInches: "14.0",
    weightGrams: 1400,
    batteryWh: 56,
    refreshRateHz: 90,
    cpuBrand: "amd",
    cpuModel: "Ryzen 7 7735U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: true,
    isActive: true,
  },
  {
    sku: "ACR-ASPIRE3-I3-8-256",
    slug: "acer-aspire-3-i3-8gb-256gb",
    brand: "acer",
    model: "Aspire 3",
    title: 'Acer Aspire 3" Core i3-1215U 8GB/256GB',
    description: "Budżetowy laptop na podstawowe zadania i internet.",
    priceCents: 179900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 22,
    ramGb: 8,
    storageGb: 256,
    screenInches: "15.6",
    weightGrams: 1700,
    batteryWh: 48,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Core i3-1215U",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "ssd",
    os: "windows",
    touchscreen: false,
    backlitKeyboard: false,
    isActive: true,
  },
  {
    sku: "ASU-CHRM14-N100-4-64",
    slug: "asus-chromebook-14-n100-4gb-64gb",
    brand: "asus",
    model: "Chromebook CX1",
    title: 'ASUS Chromebook CX1 14" Intel N100 4GB/64GB',
    description: "Prosty laptop na Chrome OS, idealny do szkoły.",
    priceCents: 129900,
    compareAtPriceCents: null,
    currency: "PLN",
    quantity: 0,
    ramGb: 4,
    storageGb: 64,
    screenInches: "14.0",
    weightGrams: 1400,
    batteryWh: 42,
    refreshRateHz: 60,
    cpuBrand: "intel",
    cpuModel: "Intel N100",
    gpuType: "integrated",
    gpuModel: null,
    storageType: "emmc",
    os: "chrome_os",
    touchscreen: false,
    backlitKeyboard: false,
    isActive: true,
  },
];

async function seed() {
  console.log("Seedowanie tabeli laptops...");
  console.log("DATABASE_URL:", process.env.DATABASE_URL);

  const inserted = await db
    .insert(laptops)
    .values(laptopSeedData)
    .onConflictDoNothing({ target: laptops.sku })
    .returning({ id: laptops.id, title: laptops.title });

  console.log(`Dodano ${inserted.length} laptopów.`);

  if (inserted.length === 0) {
    console.log(
      "Nic nie dodano - prawdopodobnie dane już istnieją (konflikt po SKU).",
    );
  }

  process.exit(0);
}

seed().catch((err) => {
  console.error("Błąd podczas seedowania:", err);
  process.exit(1);
});
